# docker-compose.override.yml
version: '3.8'
services:
  web:
    build: .
    command: sh -c "chmod +x /app/run.py && python run.py"
    environment:
      - DATABASE_URL=postgresql://abdurashid:5161@db:5432/resume_db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=abdurashid
      - POSTGRES_PASSWORD=5161
      - POSTGRES_DB=resume_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U abdurashid -d resume_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: