# docker-compose.override.yml
version: '3.8'

services:
  web:
    build: .
    command: python run.py
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/resume_db
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=resume_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
